import Link from "next/link";
import { SiteNav } from "@/components/site-nav";

export default function TermsPage() {
  return (
    <div>
      <SiteNav />
      <main className="mx-auto w-[min(calc(100%-36px),780px)] py-24">
        <div className="mb-8">
          <Link href="/" className="text-[0.85rem] text-[var(--muted)] hover:text-[var(--text)] transition-colors">
            ← Back to home
          </Link>
        </div>

        <div className="mb-10">
          <div className="mb-3 inline-flex items-center gap-2 text-[0.75rem] font-extrabold uppercase tracking-[0.12em] text-[var(--accent)]">
            <span className="block h-px w-4 bg-[var(--accent)]" />Legal
          </div>
          <h1 className="font-[family-name:var(--font-cormorant)] text-[clamp(2.5rem,4vw,3.5rem)] leading-[0.98] tracking-[-0.05em] mb-4">
            Terms of Service
          </h1>
          <p className="text-[0.9rem] text-[var(--muted)]">Last updated: April 2026</p>
        </div>

        <div className="grid gap-8 text-[0.95rem] leading-8 text-[var(--muted)]">
          {[
            {
              title: "Acceptance of terms",
              body: "By accessing or using Stablelane, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the product. Stablelane is currently in testnet preview and is provided for evaluation purposes."
            },
            {
              title: "Testnet status",
              body: "Stablelane currently operates on Arc testnet. All transactions, invoices, and escrow operations are simulated and do not involve real funds. Do not send real assets to any addresses generated by this application during the testnet period. Stablelane is not responsible for any loss of funds resulting from misuse of testnet addresses."
            },
            {
              title: "Your account",
              body: "You are responsible for maintaining the security of your account credentials and wallet. Stablelane is not responsible for any loss resulting from unauthorized access to your account. You must provide accurate information when creating an account and keep it up to date."
            },
            {
              title: "Acceptable use",
              body: "You agree not to use Stablelane for any unlawful purpose, to transmit fraudulent invoices, to impersonate other users or businesses, or to attempt to gain unauthorized access to any part of the product. We reserve the right to suspend accounts that violate these terms."
            },
            {
              title: "Intellectual property",
              body: "The Stablelane name, logo, and product design are the property of Stablelane. Smart contracts deployed on Arc are open for inspection. The software underlying the product is proprietary unless explicitly stated otherwise."
            },
            {
              title: "No financial advice",
              body: "Stablelane is a software tool for invoice and payment management. Nothing on this platform constitutes financial, legal, or tax advice. You are solely responsible for compliance with applicable laws in your jurisdiction, including any regulations relating to stablecoin transactions."
            },
            {
              title: "Limitation of liability",
              body: "Stablelane is provided on an as-is basis during the testnet period. We make no warranties about uptime, data retention, or fitness for a particular purpose. To the maximum extent permitted by law, Stablelane is not liable for any indirect, incidental, or consequential damages."
            },
            {
              title: "Changes to terms",
              body: "We may update these terms as the product evolves. We will notify users of material changes via email or in-app notice. Continued use of the product after changes constitutes acceptance of the new terms."
            },
            {
              title: "Contact",
              body: "For questions about these terms, contact us at the email address listed on the Stablelane homepage."
            },
          ].map((section) => (
            <section key={section.title}>
              <h2 className="mb-3 text-[1.1rem] font-semibold text-[var(--text)]">{section.title}</h2>
              <p>{section.body}</p>
            </section>
          ))}
        </div>
      </main>
    </div>
  );
}
